import { normalizeVietnamese } from '../ingredient.service';

/**
 * Bảng dịch tên nguyên liệu Việt -> truy vấn tiếng Anh cho USDA FoodData Central.
 * Key đã normalize (bỏ dấu, lowercase). Ưu tiên key dài hơn (cụ thể hơn).
 */
const VI_EN_ALIASES: Array<[string, string]> = [
  // Thịt / gia cầm
  ['thit heo ba chi', 'pork belly raw'],
  ['ba chi', 'pork belly raw'],
  ['thit heo nac', 'pork loin raw'],
  ['thit nac', 'pork loin raw'],
  ['suon heo', 'pork ribs raw'],
  ['suon non', 'pork spareribs raw'],
  ['gio heo', 'pork leg raw'],
  ['chan gio', 'pork leg raw'],
  ['thit heo xay', 'pork ground raw'],
  ['thit heo', 'pork raw'],
  ['thit lon', 'pork raw'],
  ['nam bo', 'beef brisket raw'],
  ['bap bo', 'beef shank raw'],
  ['gan bo', 'beef tendon raw'],
  ['thit bo xay', 'beef ground raw'],
  ['thit bo', 'beef raw'],
  ['xuong bo', 'beef bones'],
  ['xuong heo', 'pork bones'],
  ['uc ga', 'chicken breast raw'],
  ['dui ga', 'chicken thigh raw'],
  ['canh ga', 'chicken wing raw'],
  ['thit ga', 'chicken meat raw'],
  ['ga ta', 'chicken whole raw'],
  ['ga', 'chicken whole raw'],
  ['thit vit', 'duck meat raw'],
  ['vit', 'duck meat raw'],
  ['cha lua', 'pork sausage'],
  ['gio lua', 'pork sausage'],
  ['xuc xich', 'sausage'],
  ['long heo', 'pork intestine raw'],
  ['gan heo', 'pork liver raw'],
  ['tiet', 'pork blood'],
  ['huyet', 'pork blood'],
  // Hải sản
  ['tom su', 'shrimp raw'],
  ['tom kho', 'shrimp dried'],
  ['tom', 'shrimp raw'],
  ['ca hoi', 'salmon raw'],
  ['ca ngu', 'tuna raw'],
  ['ca loc', 'snakehead fish raw'],
  ['ca basa', 'basa fish raw'],
  ['ca thu', 'mackerel raw'],
  ['ca ro', 'tilapia raw'],
  ['ca dieu hong', 'tilapia raw'],
  ['ca', 'fish raw'],
  ['muc', 'squid raw'],
  ['cua', 'crab raw'],
  ['ghe', 'crab raw'],
  ['ngheu', 'clam raw'],
  ['so', 'clam raw'],
  ['oc', 'snail raw'],
  // Tinh bột
  ['gao nep', 'rice glutinous raw'],
  ['gao te', 'rice white long grain raw'],
  ['gao', 'rice white long grain raw'],
  ['com', 'rice white cooked'],
  ['bun', 'rice noodles'],
  ['banh pho', 'rice noodles'],
  ['pho', 'rice noodles'],
  ['hu tieu', 'rice noodles'],
  ['mi trung', 'egg noodles'],
  ['mi', 'noodles'],
  ['mien', 'glass noodles mung bean'],
  ['bot gao', 'rice flour'],
  ['bot mi', 'wheat flour'],
  ['bot nang', 'tapioca starch'],
  ['bot bap', 'corn starch'],
  ['banh mi', 'bread french'],
  ['banh trang', 'rice paper'],
  ['khoai tay', 'potato raw'],
  ['khoai lang', 'sweet potato raw'],
  ['khoai mon', 'taro raw'],
  ['san', 'cassava raw'],
  ['bap', 'corn sweet raw'],
  // Rau củ
  ['hanh tay', 'onion raw'],
  ['hanh tim', 'shallot raw'],
  ['hanh la', 'green onion raw'],
  ['hanh', 'onion raw'],
  ['toi', 'garlic raw'],
  ['gung', 'ginger root raw'],
  ['sa', 'lemongrass raw'],
  ['nghe', 'turmeric root'],
  ['ot', 'chili pepper raw'],
  ['ca chua', 'tomato raw'],
  ['ca rot', 'carrot raw'],
  ['ca tim', 'eggplant raw'],
  ['bap cai', 'cabbage raw'],
  ['cai thao', 'chinese cabbage napa raw'],
  ['cai thia', 'bok choy raw'],
  ['cai ngot', 'chinese cabbage raw'],
  ['rau muong', 'water spinach raw'],
  ['rau cai', 'mustard greens raw'],
  ['rau bina', 'spinach raw'],
  ['dua leo', 'cucumber raw'],
  ['dua chuot', 'cucumber raw'],
  ['bi do', 'pumpkin raw'],
  ['bi xanh', 'wax gourd raw'],
  ['bi dao', 'wax gourd raw'],
  ['kho qua', 'bitter melon raw'],
  ['muop', 'luffa gourd raw'],
  ['su su', 'chayote raw'],
  ['dau bap', 'okra raw'],
  ['gia do', 'mung bean sprouts raw'],
  ['gia', 'mung bean sprouts raw'],
  ['bap chuoi', 'banana flower'],
  ['xa lach', 'lettuce raw'],
  ['rau thom', 'herbs fresh'],
  ['rau ram', 'coriander leaves raw'],
  ['rau mui', 'coriander leaves raw'],
  ['ngo gai', 'coriander leaves raw'],
  ['ngo', 'coriander leaves raw'],
  ['hung que', 'basil fresh'],
  ['hung lui', 'mint fresh'],
  ['tia to', 'perilla leaves'],
  ['la lot', 'betel leaves'],
  ['nam huong', 'shiitake mushroom'],
  ['nam rom', 'straw mushroom'],
  ['nam kim cham', 'enoki mushroom'],
  ['nam', 'mushroom raw'],
  ['dau hu', 'tofu firm'],
  ['dau phu', 'tofu firm'],
  ['tau hu', 'tofu firm'],
  ['dau xanh', 'mung beans raw'],
  ['dau do', 'red beans raw'],
  ['dau nanh', 'soybeans raw'],
  ['dau phong', 'peanuts raw'],
  ['lac', 'peanuts raw'],
  ['me', 'sesame seeds'],
  ['dua', 'coconut meat raw'],
  ['chanh', 'lime raw'],
  ['tac', 'kumquat raw'],
  ['me chua', 'tamarind'],
  ['thom', 'pineapple raw'],
  ['dua hau', 'watermelon raw'],
  ['chuoi', 'banana raw'],
  ['xoai', 'mango raw'],
  // Gia vị
  ['nuoc mam', 'fish sauce'],
  ['nuoc tuong', 'soy sauce'],
  ['xi dau', 'soy sauce'],
  ['dau hao', 'oyster sauce'],
  ['tuong ot', 'chili sauce'],
  ['tuong den', 'hoisin sauce'],
  ['mam ruoc', 'shrimp paste'],
  ['mam tom', 'shrimp paste'],
  ['muoi', 'salt table'],
  ['duong phen', 'sugar brown'],
  ['duong', 'sugar granulated'],
  ['bot ngot', 'monosodium glutamate'],
  ['hat nem', 'bouillon granules'],
  ['tieu', 'pepper black'],
  ['dau an', 'oil vegetable'],
  ['dau me', 'oil sesame'],
  ['dau dieu', 'oil vegetable annatto'],
  ['mo heo', 'lard'],
  ['bo', 'butter'],
  ['giam', 'vinegar'],
  ['sa te', 'chili oil'],
  ['hoa hoi', 'star anise'],
  ['que', 'cinnamon'],
  ['thao qua', 'cardamom'],
  ['nuoc cot dua', 'coconut milk'],
  ['nuoc dua', 'coconut water'],
  ['sua dac', 'milk sweetened condensed'],
  ['sua tuoi', 'milk whole'],
  ['sua', 'milk whole'],
  ['trung ga', 'egg whole raw'],
  ['trung vit', 'egg duck whole raw'],
  ['trung cut', 'egg quail whole raw'],
  ['trung', 'egg whole raw'],
  ['nuoc loc', 'water'],
  ['nuoc', 'water'],
];

const SORTED = [...VI_EN_ALIASES].sort((a, b) => b[0].length - a[0].length);

/** Dịch tên nguyên liệu Việt sang truy vấn tiếng Anh cho USDA. Trả null nếu quá mơ hồ. */
export function toEnglishIngredientQuery(name: string): string | null {
  const normalized = normalizeVietnamese(name);
  if (!normalized) return null;
  const padded = ` ${normalized} `;
  for (const [vi, en] of SORTED) {
    if (normalized === vi || padded.includes(` ${vi} `)) return en;
  }
  // Fallback: nếu tên đã là tiếng Anh/ASCII (không có dấu), dùng trực tiếp.
  if (/^[a-z0-9 ]+$/.test(name.trim().toLowerCase()) && name.trim().length >= 3) {
    return name.trim().toLowerCase();
  }
  return null;
}
