/**
 * Dataset rút gọn từ "Bảng thành phần thực phẩm Việt Nam 2007" — Viện Dinh dưỡng Quốc gia (Bộ Y tế).
 * Giá trị trên 100g phần ăn được. Mã fctCode theo bảng gốc (nhóm.số thứ tự) để tham chiếu.
 * Chỉ bao gồm ~150 thực phẩm phổ biến trong món Việt; nguyên liệu khác fallback USDA FDC.
 */
export interface VietnamFctFood {
  fctCode: string;
  nameVi: string;
  nameEn?: string;
  /** Alias đã normalize (không dấu) để so khớp. */
  aliases: string[];
  kcal: number;
  protein: number;
  fat: number;
  carbs: number;
  fiber: number;
  sodiumMg: number;
}

export const VIETNAM_FCT_2007_SOURCE = {
  provider: 'VIETNAM_FCT_2007',
  title: 'Bảng thành phần thực phẩm Việt Nam 2007 - Viện Dinh dưỡng Quốc gia (Bộ Y tế)',
  url: 'https://viendinhduong.vn/vi/bang-thanh-phan-thuc-pham-viet-nam.html',
};

export const VIETNAM_FCT_2007: VietnamFctFood[] = [
  // ── 1. Ngũ cốc & sản phẩm chế biến ──────────────────────────────────────
  { fctCode: '1.001', nameVi: 'Gạo tẻ', nameEn: 'White rice, raw', aliases: ['gao te', 'gao', 'gao thom', 'gao lai', 'gao thom lai', 'gao trang'], kcal: 344, protein: 7.9, fat: 1.0, carbs: 75.9, fiber: 0.4, sodiumMg: 5 },
  { fctCode: '1.004', nameVi: 'Gạo nếp', nameEn: 'Glutinous rice, raw', aliases: ['gao nep', 'nep', 'nep cai'], kcal: 344, protein: 8.6, fat: 1.5, carbs: 74.9, fiber: 0.6, sodiumMg: 3 },
  { fctCode: '1.005', nameVi: 'Gạo lứt', nameEn: 'Brown rice', aliases: ['gao lut', 'gao luc'], kcal: 345, protein: 7.5, fat: 2.7, carbs: 72.8, fiber: 3.4, sodiumMg: 5 },
  { fctCode: '1.010', nameVi: 'Cơm tẻ', nameEn: 'Cooked white rice', aliases: ['com', 'com trang', 'com te', 'com nguoi'], kcal: 130, protein: 2.7, fat: 0.3, carbs: 28.2, fiber: 0.3, sodiumMg: 1 },
  { fctCode: '1.020', nameVi: 'Bún', nameEn: 'Rice vermicelli, fresh', aliases: ['bun', 'bun tuoi', 'bun soi', 'bun bo', 'bun soi to'], kcal: 110, protein: 1.7, fat: 0.0, carbs: 25.7, fiber: 0.5, sodiumMg: 15 },
  { fctCode: '1.021', nameVi: 'Bánh phở', nameEn: 'Pho rice noodle, fresh', aliases: ['banh pho', 'pho', 'banh pho tuoi', 'hu tieu', 'hu tieu tuoi', 'banh canh', 'banh canh tuoi', 'mi quang', 'cao lau', 'banh uot', 'banh cuon'], kcal: 143, protein: 3.2, fat: 0.4, carbs: 32.1, fiber: 0.5, sodiumMg: 20 },
  { fctCode: '1.025', nameVi: 'Mì sợi', nameEn: 'Egg noodle, dried', aliases: ['mi soi', 'mi trung', 'mi vang', 'mi', 'mi tuoi'], kcal: 349, protein: 11.0, fat: 0.9, carbs: 74.2, fiber: 0.5, sodiumMg: 180 },
  { fctCode: '1.026', nameVi: 'Mì ăn liền', nameEn: 'Instant noodle', aliases: ['mi an lien', 'mi goi', 'mi tom'], kcal: 436, protein: 9.0, fat: 17.0, carbs: 62.0, fiber: 1.0, sodiumMg: 1800 },
  { fctCode: '1.030', nameVi: 'Miến dong', nameEn: 'Glass noodle', aliases: ['mien', 'mien dong', 'mien kho'], kcal: 332, protein: 0.5, fat: 0.1, carbs: 82.2, fiber: 1.5, sodiumMg: 10 },
  { fctCode: '1.040', nameVi: 'Bánh mì', nameEn: 'Vietnamese baguette', aliases: ['banh mi', 'o banh mi', 'banh mi o'], kcal: 249, protein: 7.9, fat: 0.8, carbs: 52.6, fiber: 0.2, sodiumMg: 540 },
  { fctCode: '1.045', nameVi: 'Bột mì', nameEn: 'Wheat flour', aliases: ['bot mi', 'bot mi da dung', 'bot mi so 8', 'bot mi so 11'], kcal: 346, protein: 11.0, fat: 1.1, carbs: 73.6, fiber: 0.3, sodiumMg: 2 },
  { fctCode: '1.050', nameVi: 'Bột gạo', nameEn: 'Rice flour', aliases: ['bot gao', 'bot gao te'], kcal: 359, protein: 6.6, fat: 0.5, carbs: 82.2, fiber: 0.5, sodiumMg: 3 },
  { fctCode: '1.051', nameVi: 'Bột nếp', nameEn: 'Glutinous rice flour', aliases: ['bot nep'], kcal: 362, protein: 6.5, fat: 0.8, carbs: 82.0, fiber: 0.6, sodiumMg: 3 },
  { fctCode: '1.055', nameVi: 'Bột năng', nameEn: 'Tapioca starch', aliases: ['bot nang', 'bot san', 'bot khoai mi', 'tinh bot san'], kcal: 351, protein: 0.3, fat: 0.1, carbs: 87.0, fiber: 0.4, sodiumMg: 2 },
  { fctCode: '1.056', nameVi: 'Bột bắp', nameEn: 'Corn starch', aliases: ['bot bap', 'bot ngo', 'tinh bot bap'], kcal: 351, protein: 0.3, fat: 0.1, carbs: 87.0, fiber: 0.5, sodiumMg: 5 },
  { fctCode: '1.060', nameVi: 'Bánh tráng', nameEn: 'Rice paper', aliases: ['banh trang', 'banh da nem', 'banh trang cuon', 'banh da'], kcal: 333, protein: 4.0, fat: 0.2, carbs: 78.9, fiber: 0.3, sodiumMg: 300 },
  { fctCode: '1.070', nameVi: 'Ngô (bắp) tươi', nameEn: 'Sweet corn', aliases: ['bap', 'ngo', 'bap my', 'ngo ngot', 'bap ngot', 'hat bap'], kcal: 196, protein: 4.1, fat: 2.3, carbs: 39.6, fiber: 1.2, sodiumMg: 15 },
  { fctCode: '1.080', nameVi: 'Bánh đa', nameEn: 'Rice cracker', aliases: ['banh da nuong', 'banh da do', 'banh da cua'], kcal: 350, protein: 5.0, fat: 1.0, carbs: 78.0, fiber: 0.5, sodiumMg: 250 },

  // ── 2. Khoai củ ───────────────────────────────────────────────────────────
  { fctCode: '2.001', nameVi: 'Khoai lang', nameEn: 'Sweet potato', aliases: ['khoai lang'], kcal: 119, protein: 0.8, fat: 0.2, carbs: 28.5, fiber: 1.3, sodiumMg: 55 },
  { fctCode: '2.005', nameVi: 'Khoai tây', nameEn: 'Potato', aliases: ['khoai tay'], kcal: 93, protein: 2.0, fat: 0.1, carbs: 21.0, fiber: 1.0, sodiumMg: 6 },
  { fctCode: '2.010', nameVi: 'Khoai môn', nameEn: 'Taro', aliases: ['khoai mon', 'khoai so', 'mon'], kcal: 109, protein: 1.5, fat: 0.2, carbs: 25.2, fiber: 1.2, sodiumMg: 11 },
  { fctCode: '2.015', nameVi: 'Sắn (khoai mì)', nameEn: 'Cassava', aliases: ['san', 'khoai mi'], kcal: 152, protein: 1.1, fat: 0.2, carbs: 36.4, fiber: 1.5, sodiumMg: 14 },
  { fctCode: '2.020', nameVi: 'Củ sen', nameEn: 'Lotus root', aliases: ['cu sen'], kcal: 74, protein: 2.6, fat: 0.1, carbs: 15.0, fiber: 1.2, sodiumMg: 40 },
  { fctCode: '2.025', nameVi: 'Củ đậu', nameEn: 'Jicama', aliases: ['cu dau', 'cu san nuoc'], kcal: 29, protein: 1.0, fat: 0.0, carbs: 6.0, fiber: 1.0, sodiumMg: 4 },

  // ── 3. Đậu đỗ, hạt ────────────────────────────────────────────────────────
  { fctCode: '3.001', nameVi: 'Đậu nành (hạt)', nameEn: 'Soybean', aliases: ['dau nanh', 'dau tuong', 'hat dau nanh'], kcal: 400, protein: 34.0, fat: 18.4, carbs: 24.6, fiber: 4.5, sodiumMg: 2 },
  { fctCode: '3.005', nameVi: 'Đậu xanh', nameEn: 'Mung bean', aliases: ['dau xanh', 'dau xanh cat vo', 'dau xanh khong vo'], kcal: 328, protein: 23.4, fat: 2.4, carbs: 53.1, fiber: 4.7, sodiumMg: 6 },
  { fctCode: '3.006', nameVi: 'Đậu đen', nameEn: 'Black bean', aliases: ['dau den'], kcal: 325, protein: 24.2, fat: 1.7, carbs: 53.3, fiber: 4.0, sodiumMg: 5 },
  { fctCode: '3.007', nameVi: 'Đậu đỏ', nameEn: 'Red bean', aliases: ['dau do'], kcal: 341, protein: 21.4, fat: 0.5, carbs: 61.9, fiber: 4.6, sodiumMg: 5 },
  { fctCode: '3.010', nameVi: 'Đậu phộng (lạc)', nameEn: 'Peanut', aliases: ['dau phong', 'lac', 'dau phong rang', 'lac rang'], kcal: 573, protein: 27.5, fat: 44.5, carbs: 15.5, fiber: 2.5, sodiumMg: 3 },
  { fctCode: '3.015', nameVi: 'Mè (vừng)', nameEn: 'Sesame seed', aliases: ['me', 'vung', 'me trang', 'me den', 'me rang', 'vung rang'], kcal: 568, protein: 20.1, fat: 46.4, carbs: 17.6, fiber: 3.5, sodiumMg: 10 },
  { fctCode: '3.020', nameVi: 'Đậu hũ (đậu phụ)', nameEn: 'Tofu', aliases: ['dau hu', 'dau phu', 'tau hu', 'dau hu non', 'dau hu trang', 'dau hu chien'], kcal: 95, protein: 10.9, fat: 5.4, carbs: 0.7, fiber: 0.4, sodiumMg: 7 },
  { fctCode: '3.025', nameVi: 'Giá đỗ', nameEn: 'Bean sprouts', aliases: ['gia do', 'gia', 'gia dau xanh', 'gia song'], kcal: 44, protein: 5.5, fat: 0.0, carbs: 5.3, fiber: 2.0, sodiumMg: 6 },
  { fctCode: '3.030', nameVi: 'Hạt điều', nameEn: 'Cashew', aliases: ['hat dieu', 'dieu'], kcal: 605, protein: 18.4, fat: 46.3, carbs: 28.7, fiber: 0.6, sodiumMg: 12 },
  { fctCode: '3.035', nameVi: 'Đậu que (cô ve)', nameEn: 'Green bean', aliases: ['dau que', 'dau co ve', 'dau dua'], kcal: 31, protein: 1.8, fat: 0.1, carbs: 7.0, fiber: 2.7, sodiumMg: 6 },
  { fctCode: '3.040', nameVi: 'Đậu Hà Lan', nameEn: 'Snow pea', aliases: ['dau ha lan', 'dau ho lan'], kcal: 42, protein: 2.8, fat: 0.2, carbs: 7.5, fiber: 2.6, sodiumMg: 4 },

  // ── 4. Rau củ ─────────────────────────────────────────────────────────────
  { fctCode: '4.001', nameVi: 'Rau muống', nameEn: 'Water spinach', aliases: ['rau muong', 'rau muong che', 'rau muong bao'], kcal: 23, protein: 3.2, fat: 0.0, carbs: 2.5, fiber: 1.0, sodiumMg: 113 },
  { fctCode: '4.005', nameVi: 'Cải xanh (cải bẹ xanh)', nameEn: 'Mustard green', aliases: ['cai xanh', 'cai be xanh', 'rau cai', 'cai cay'], kcal: 16, protein: 1.7, fat: 0.0, carbs: 2.1, fiber: 1.8, sodiumMg: 20 },
  { fctCode: '4.006', nameVi: 'Cải ngọt', nameEn: 'Choy sum', aliases: ['cai ngot', 'rau cai ngot'], kcal: 14, protein: 1.4, fat: 0.1, carbs: 2.0, fiber: 1.5, sodiumMg: 30 },
  { fctCode: '4.007', nameVi: 'Cải thìa (cải chíp)', nameEn: 'Bok choy', aliases: ['cai thia', 'cai chip', 'cai be trang'], kcal: 13, protein: 1.5, fat: 0.2, carbs: 1.5, fiber: 1.0, sodiumMg: 65 },
  { fctCode: '4.010', nameVi: 'Bắp cải', nameEn: 'Cabbage', aliases: ['bap cai', 'cai bap', 'bap cai trang'], kcal: 29, protein: 1.8, fat: 0.1, carbs: 5.4, fiber: 1.6, sodiumMg: 18 },
  { fctCode: '4.011', nameVi: 'Cải thảo', nameEn: 'Napa cabbage', aliases: ['cai thao', 'cai bao'], kcal: 14, protein: 1.1, fat: 0.1, carbs: 2.5, fiber: 1.2, sodiumMg: 9 },
  { fctCode: '4.015', nameVi: 'Súp lơ (bông cải)', nameEn: 'Cauliflower / broccoli', aliases: ['sup lo', 'bong cai', 'bong cai xanh', 'bong cai trang', 'sup lo xanh', 'sup lo trang'], kcal: 30, protein: 2.5, fat: 0.1, carbs: 4.9, fiber: 0.9, sodiumMg: 20 },
  { fctCode: '4.020', nameVi: 'Rau dền', nameEn: 'Amaranth', aliases: ['rau den', 'den', 'rau den do'], kcal: 25, protein: 2.3, fat: 0.3, carbs: 2.5, fiber: 1.1, sodiumMg: 42 },
  { fctCode: '4.021', nameVi: 'Rau mồng tơi', nameEn: 'Malabar spinach', aliases: ['mong toi', 'rau mong toi'], kcal: 14, protein: 2.0, fat: 0.0, carbs: 1.4, fiber: 2.5, sodiumMg: 30 },
  { fctCode: '4.022', nameVi: 'Rau ngót', nameEn: 'Sweet leaf', aliases: ['rau ngot', 'bo ngot'], kcal: 36, protein: 5.3, fat: 0.0, carbs: 3.4, fiber: 2.5, sodiumMg: 25 },
  { fctCode: '4.023', nameVi: 'Rau đay', nameEn: 'Jute leaf', aliases: ['rau day'], kcal: 24, protein: 2.8, fat: 0.0, carbs: 3.2, fiber: 1.5, sodiumMg: 20 },
  { fctCode: '4.025', nameVi: 'Rau xà lách', nameEn: 'Lettuce', aliases: ['xa lach', 'rau xa lach', 'rau diep', 'xa lach xoong'], kcal: 17, protein: 1.5, fat: 0.2, carbs: 2.2, fiber: 0.5, sodiumMg: 8 },
  { fctCode: '4.030', nameVi: 'Rau thơm (húng, quế)', nameEn: 'Vietnamese herbs', aliases: ['rau thom', 'hung que', 'hung', 'rau que', 'hung lui', 'rau hung', 'rau ram', 'tia to', 'kinh gioi', 'rau gia vi', 'rau song', 'rau an kem', 'diep ca', 'rau mui', 'ngo', 'ngo gai', 'ngo om', 'rau ngo', 'ngo ri', 'hung cay', 'bac ha', 'rau bac ha', 'la lot'], kcal: 26, protein: 2.5, fat: 0.5, carbs: 3.0, fiber: 1.8, sodiumMg: 15 },
  { fctCode: '4.040', nameVi: 'Hành lá', nameEn: 'Green onion', aliases: ['hanh la', 'hanh', 'hanh hoa', 'hanh xanh', 'dau hanh'], kcal: 22, protein: 1.3, fat: 0.0, carbs: 4.3, fiber: 0.9, sodiumMg: 17 },
  { fctCode: '4.041', nameVi: 'Hành tây', nameEn: 'Onion', aliases: ['hanh tay', 'cu hanh tay'], kcal: 41, protein: 1.8, fat: 0.1, carbs: 8.3, fiber: 0.7, sodiumMg: 4 },
  { fctCode: '4.042', nameVi: 'Hành tím (hành củ)', nameEn: 'Shallot', aliases: ['hanh tim', 'hanh cu', 'cu hanh tim', 'hanh kho', 'hanh phi'], kcal: 72, protein: 2.5, fat: 0.1, carbs: 15.0, fiber: 3.2, sodiumMg: 12 },
  { fctCode: '4.043', nameVi: 'Tỏi', nameEn: 'Garlic', aliases: ['toi', 'cu toi', 'tep toi', 'toi bam', 'toi phi'], kcal: 121, protein: 6.0, fat: 0.5, carbs: 23.0, fiber: 1.5, sodiumMg: 17 },
  { fctCode: '4.044', nameVi: 'Gừng', nameEn: 'Ginger', aliases: ['gung', 'cu gung', 'gung tuoi'], kcal: 25, protein: 0.4, fat: 0.0, carbs: 5.8, fiber: 3.3, sodiumMg: 13 },
  { fctCode: '4.045', nameVi: 'Sả', nameEn: 'Lemongrass', aliases: ['sa', 'cay sa', 'sa cay', 'sa bam', 'xa'], kcal: 99, protein: 1.8, fat: 0.5, carbs: 25.3, fiber: 0.0, sodiumMg: 6 },
  { fctCode: '4.046', nameVi: 'Nghệ tươi', nameEn: 'Fresh turmeric', aliases: ['nghe', 'nghe tuoi', 'cu nghe'], kcal: 312, protein: 9.7, fat: 3.3, carbs: 67.1, fiber: 22.7, sodiumMg: 27 },
  { fctCode: '4.047', nameVi: 'Riềng', nameEn: 'Galangal', aliases: ['rieng', 'cu rieng'], kcal: 71, protein: 1.0, fat: 0.6, carbs: 16.0, fiber: 2.4, sodiumMg: 15 },
  { fctCode: '4.050', nameVi: 'Ớt tươi', nameEn: 'Fresh chili', aliases: ['ot', 'ot tuoi', 'ot hiem', 'ot sung', 'ot do', 'ot chi thien', 'ot xanh', 'trai ot'], kcal: 23, protein: 1.3, fat: 0.0, carbs: 5.7, fiber: 1.4, sodiumMg: 9 },
  { fctCode: '4.051', nameVi: 'Ớt chuông', nameEn: 'Bell pepper', aliases: ['ot chuong', 'ot da lat', 'ot ngot'], kcal: 26, protein: 1.0, fat: 0.3, carbs: 6.0, fiber: 2.1, sodiumMg: 4 },
  { fctCode: '4.055', nameVi: 'Cà chua', nameEn: 'Tomato', aliases: ['ca chua', 'ca chua bi', 'trai ca chua'], kcal: 20, protein: 0.6, fat: 0.2, carbs: 4.2, fiber: 0.8, sodiumMg: 12 },
  { fctCode: '4.056', nameVi: 'Cà tím', nameEn: 'Eggplant', aliases: ['ca tim', 'ca dai'], kcal: 22, protein: 1.0, fat: 0.0, carbs: 4.5, fiber: 1.5, sodiumMg: 4 },
  { fctCode: '4.057', nameVi: 'Cà pháo', nameEn: 'Thai eggplant', aliases: ['ca phao'], kcal: 20, protein: 1.5, fat: 0.0, carbs: 3.0, fiber: 1.5, sodiumMg: 6 },
  { fctCode: '4.060', nameVi: 'Cà rốt', nameEn: 'Carrot', aliases: ['ca rot', 'cu ca rot'], kcal: 39, protein: 1.5, fat: 0.2, carbs: 7.8, fiber: 1.2, sodiumMg: 60 },
  { fctCode: '4.061', nameVi: 'Củ cải trắng', nameEn: 'Daikon', aliases: ['cu cai', 'cu cai trang'], kcal: 21, protein: 1.5, fat: 0.1, carbs: 3.7, fiber: 1.5, sodiumMg: 18 },
  { fctCode: '4.065', nameVi: 'Dưa leo (dưa chuột)', nameEn: 'Cucumber', aliases: ['dua leo', 'dua chuot'], kcal: 16, protein: 0.8, fat: 0.1, carbs: 2.9, fiber: 0.7, sodiumMg: 2 },
  { fctCode: '4.066', nameVi: 'Bí đao (bí xanh)', nameEn: 'Winter melon', aliases: ['bi dao', 'bi xanh'], kcal: 12, protein: 0.6, fat: 0.0, carbs: 2.4, fiber: 1.0, sodiumMg: 6 },
  { fctCode: '4.067', nameVi: 'Bí đỏ', nameEn: 'Pumpkin', aliases: ['bi do', 'bi ngo', 'bi ro'], kcal: 27, protein: 0.3, fat: 0.1, carbs: 6.2, fiber: 0.7, sodiumMg: 1 },
  { fctCode: '4.068', nameVi: 'Mướp', nameEn: 'Luffa', aliases: ['muop', 'muop huong'], kcal: 17, protein: 0.9, fat: 0.1, carbs: 3.0, fiber: 0.5, sodiumMg: 8 },
  { fctCode: '4.069', nameVi: 'Khổ qua (mướp đắng)', nameEn: 'Bitter melon', aliases: ['kho qua', 'muop dang'], kcal: 16, protein: 0.9, fat: 0.1, carbs: 3.0, fiber: 1.1, sodiumMg: 5 },
  { fctCode: '4.070', nameVi: 'Su hào', nameEn: 'Kohlrabi', aliases: ['su hao'], kcal: 36, protein: 2.8, fat: 0.0, carbs: 6.3, fiber: 1.7, sodiumMg: 20 },
  { fctCode: '4.071', nameVi: 'Su su', nameEn: 'Chayote', aliases: ['su su'], kcal: 18, protein: 0.8, fat: 0.1, carbs: 3.9, fiber: 1.0, sodiumMg: 2 },
  { fctCode: '4.072', nameVi: 'Đu đủ xanh', nameEn: 'Green papaya', aliases: ['du du xanh', 'du du bao'], kcal: 24, protein: 0.8, fat: 0.1, carbs: 5.0, fiber: 1.0, sodiumMg: 3 },
  { fctCode: '4.075', nameVi: 'Nấm rơm', nameEn: 'Straw mushroom', aliases: ['nam rom', 'nam'], kcal: 31, protein: 3.6, fat: 0.3, carbs: 3.4, fiber: 1.1, sodiumMg: 14 },
  { fctCode: '4.076', nameVi: 'Nấm hương (đông cô)', nameEn: 'Shiitake', aliases: ['nam huong', 'nam dong co', 'nam huong kho'], kcal: 35, protein: 2.2, fat: 0.5, carbs: 6.8, fiber: 2.5, sodiumMg: 9 },
  { fctCode: '4.077', nameVi: 'Mộc nhĩ (nấm mèo)', nameEn: 'Wood ear mushroom', aliases: ['moc nhi', 'nam meo'], kcal: 25, protein: 0.5, fat: 0.1, carbs: 6.0, fiber: 7.0, sodiumMg: 10 },
  { fctCode: '4.078', nameVi: 'Nấm kim châm', nameEn: 'Enoki', aliases: ['nam kim cham'], kcal: 37, protein: 2.7, fat: 0.3, carbs: 7.8, fiber: 2.7, sodiumMg: 3 },
  { fctCode: '4.080', nameVi: 'Măng tươi', nameEn: 'Bamboo shoot', aliases: ['mang', 'mang tuoi', 'mang chua', 'mang kho'], kcal: 14, protein: 1.7, fat: 0.1, carbs: 1.7, fiber: 4.1, sodiumMg: 4 },
  { fctCode: '4.081', nameVi: 'Bắp chuối (hoa chuối)', nameEn: 'Banana blossom', aliases: ['bap chuoi', 'hoa chuoi'], kcal: 23, protein: 1.5, fat: 0.3, carbs: 4.0, fiber: 1.5, sodiumMg: 10 },
  { fctCode: '4.082', nameVi: 'Rau nhút / rau ngổ', nameEn: 'Water mimosa', aliases: ['rau nhut', 'rau ngo om'], kcal: 20, protein: 2.0, fat: 0.1, carbs: 3.0, fiber: 1.5, sodiumMg: 10 },
  { fctCode: '4.085', nameVi: 'Dưa cải muối', nameEn: 'Pickled mustard', aliases: ['dua cai', 'dua cai muoi', 'dua chua', 'cai chua'], kcal: 15, protein: 1.0, fat: 0.1, carbs: 2.5, fiber: 1.5, sodiumMg: 900 },
  { fctCode: '4.090', nameVi: 'Lá chanh', nameEn: 'Kaffir lime leaf', aliases: ['la chanh'], kcal: 30, protein: 2.0, fat: 0.5, carbs: 5.0, fiber: 2.0, sodiumMg: 5 },
  { fctCode: '4.091', nameVi: 'Hẹ', nameEn: 'Garlic chives', aliases: ['he', 'la he'], kcal: 23, protein: 2.2, fat: 0.3, carbs: 3.6, fiber: 1.5, sodiumMg: 5 },
  { fctCode: '4.092', nameVi: 'Rong biển', nameEn: 'Seaweed', aliases: ['rong bien', 'tao bien', 'la rong bien'], kcal: 45, protein: 5.8, fat: 0.3, carbs: 8.1, fiber: 1.3, sodiumMg: 230 },

  // ── 5. Quả chín ───────────────────────────────────────────────────────────
  { fctCode: '5.001', nameVi: 'Chanh', nameEn: 'Lime', aliases: ['chanh', 'chanh tuoi', 'nuoc cot chanh', 'nuoc chanh', 'trai chanh'], kcal: 23, protein: 0.9, fat: 0.0, carbs: 4.8, fiber: 1.3, sodiumMg: 2 },
  { fctCode: '5.002', nameVi: 'Tắc (quất)', nameEn: 'Calamansi', aliases: ['tac', 'quat', 'trai tac'], kcal: 29, protein: 0.9, fat: 0.1, carbs: 6.0, fiber: 1.5, sodiumMg: 2 },
  { fctCode: '5.005', nameVi: 'Dứa (thơm)', nameEn: 'Pineapple', aliases: ['dua', 'thom', 'khom', 'trai thom'], kcal: 29, protein: 0.8, fat: 0.0, carbs: 6.5, fiber: 0.8, sodiumMg: 1 },
  { fctCode: '5.010', nameVi: 'Me chín', nameEn: 'Tamarind', aliases: ['me', 'me chin', 'me chua', 'nuoc cot me', 'me vat'], kcal: 239, protein: 2.8, fat: 0.6, carbs: 62.5, fiber: 5.1, sodiumMg: 28 },
  { fctCode: '5.015', nameVi: 'Dừa (cùi)', nameEn: 'Coconut meat', aliases: ['cui dua', 'dua nao', 'dua kho', 'dua bao'], kcal: 368, protein: 4.8, fat: 36.0, carbs: 6.2, fiber: 4.2, sodiumMg: 20 },
  { fctCode: '5.016', nameVi: 'Nước cốt dừa', nameEn: 'Coconut milk', aliases: ['nuoc cot dua', 'cot dua', 'nuoc dua dao'], kcal: 230, protein: 2.3, fat: 23.8, carbs: 5.5, fiber: 2.2, sodiumMg: 15 },
  { fctCode: '5.017', nameVi: 'Nước dừa tươi', nameEn: 'Coconut water', aliases: ['nuoc dua', 'nuoc dua tuoi', 'dua tuoi'], kcal: 19, protein: 0.7, fat: 0.2, carbs: 3.7, fiber: 1.1, sodiumMg: 105 },
  { fctCode: '5.020', nameVi: 'Chuối chín', nameEn: 'Banana', aliases: ['chuoi', 'chuoi chin', 'chuoi tieu', 'chuoi su'], kcal: 97, protein: 1.5, fat: 0.2, carbs: 22.2, fiber: 0.8, sodiumMg: 1 },
  { fctCode: '5.021', nameVi: 'Xoài xanh', nameEn: 'Green mango', aliases: ['xoai', 'xoai xanh', 'xoai chin'], kcal: 62, protein: 0.6, fat: 0.3, carbs: 14.1, fiber: 1.6, sodiumMg: 2 },
  { fctCode: '5.022', nameVi: 'Táo', nameEn: 'Apple', aliases: ['tao', 'qua tao'], kcal: 47, protein: 0.5, fat: 0.0, carbs: 11.3, fiber: 0.8, sodiumMg: 1 },
  { fctCode: '5.023', nameVi: 'Cam', nameEn: 'Orange', aliases: ['cam', 'nuoc cam'], kcal: 37, protein: 0.9, fat: 0.1, carbs: 8.3, fiber: 1.4, sodiumMg: 2 },
  { fctCode: '5.024', nameVi: 'Dâu tây', nameEn: 'Strawberry', aliases: ['dau tay', 'dau'], kcal: 43, protein: 1.8, fat: 0.4, carbs: 7.7, fiber: 4.0, sodiumMg: 2 },
  { fctCode: '5.025', nameVi: 'Bơ', nameEn: 'Avocado', aliases: ['bo trai', 'trai bo', 'qua bo'], kcal: 167, protein: 1.7, fat: 15.2, carbs: 4.0, fiber: 1.6, sodiumMg: 7 },
  { fctCode: '5.026', nameVi: 'Dưa hấu', nameEn: 'Watermelon', aliases: ['dua hau'], kcal: 16, protein: 1.2, fat: 0.2, carbs: 2.3, fiber: 0.5, sodiumMg: 3 },
  { fctCode: '5.027', nameVi: 'Mít', nameEn: 'Jackfruit', aliases: ['mit', 'mit non', 'mit chin'], kcal: 48, protein: 0.6, fat: 0.3, carbs: 11.4, fiber: 1.2, sodiumMg: 2 },
  { fctCode: '5.028', nameVi: 'Nhãn / Vải', nameEn: 'Longan / Lychee', aliases: ['nhan', 'vai', 'long nhan'], kcal: 48, protein: 0.9, fat: 0.1, carbs: 11.0, fiber: 1.0, sodiumMg: 2 },

  // ── 6. Thịt & sản phẩm ────────────────────────────────────────────────────
  { fctCode: '6.001', nameVi: 'Thịt heo nạc', nameEn: 'Pork, lean', aliases: ['thit heo nac', 'thit nac', 'nac heo', 'thit heo', 'thit lon', 'thit lon nac', 'nac dam', 'nac vai', 'thit nac vai', 'thit nac dam', 'heo', 'lon', 'thit heo xay', 'thit xay', 'thit bam', 'thit heo bam', 'thit lon xay'], kcal: 139, protein: 19.0, fat: 7.0, carbs: 0.0, fiber: 0.0, sodiumMg: 76 },
  { fctCode: '6.002', nameVi: 'Thịt heo ba chỉ', nameEn: 'Pork belly', aliases: ['ba chi', 'thit ba chi', 'thit heo ba chi', 'ba roi', 'thit ba roi', 'thit lon ba chi', 'ba chi heo'], kcal: 260, protein: 16.5, fat: 21.5, carbs: 0.0, fiber: 0.0, sodiumMg: 55 },
  { fctCode: '6.003', nameVi: 'Thịt heo mỡ', nameEn: 'Pork fat', aliases: ['mo heo', 'thit mo', 'mo lon', 'top mo'], kcal: 394, protein: 14.5, fat: 37.3, carbs: 0.0, fiber: 0.0, sodiumMg: 40 },
  { fctCode: '6.004', nameVi: 'Sườn heo', nameEn: 'Pork ribs', aliases: ['suon heo', 'suon', 'suon non', 'suon lon', 'suon cot let', 'cot let'], kcal: 187, protein: 17.9, fat: 12.8, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '6.005', nameVi: 'Giò heo (chân giò)', nameEn: 'Pork hock', aliases: ['gio heo', 'chan gio', 'mong gio', 'gio lon', 'chan gio heo', 'gio heo rut xuong', 'bap gio', 'chan gio truoc'], kcal: 230, protein: 15.7, fat: 18.6, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '6.006', nameVi: 'Xương heo', nameEn: 'Pork bones', aliases: ['xuong heo', 'xuong ong', 'xuong lon', 'xuong ong heo', 'xuong', 'xuong suon'], kcal: 110, protein: 10.0, fat: 7.5, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '6.007', nameVi: 'Da heo (bì)', nameEn: 'Pork skin', aliases: ['da heo', 'bi heo', 'bi', 'da lon'], kcal: 118, protein: 23.3, fat: 2.7, carbs: 0.0, fiber: 0.0, sodiumMg: 75 },
  { fctCode: '6.008', nameVi: 'Lòng heo', nameEn: 'Pork offal', aliases: ['long heo', 'long non', 'long lon', 'ruot heo', 'da day heo', 'bao tu heo', 'gan heo', 'tim heo', 'cat heo', 'doi truong'], kcal: 160, protein: 16.0, fat: 10.5, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '6.009', nameVi: 'Huyết heo', nameEn: 'Pork blood', aliases: ['huyet heo', 'huyet', 'tiet heo', 'tiet', 'huyet luoc'], kcal: 44, protein: 10.0, fat: 0.3, carbs: 0.3, fiber: 0.0, sodiumMg: 200 },
  { fctCode: '6.010', nameVi: 'Thịt bò nạc', nameEn: 'Beef, lean', aliases: ['thit bo', 'bo', 'thit bo nac', 'bo nac', 'bo phi le', 'phi le bo', 'thit bo thai', 'thit bo xay', 'bo xay', 'thit bo tai', 'bo tai', 'thit bo philê'], kcal: 118, protein: 21.0, fat: 3.8, carbs: 0.0, fiber: 0.0, sodiumMg: 83 },
  { fctCode: '6.011', nameVi: 'Nạm bò (ba chỉ bò)', nameEn: 'Beef brisket', aliases: ['nam bo', 'bo nam', 'ba chi bo', 'thit nam', 'nam', 'gau bo', 'bo gau'], kcal: 197, protein: 18.0, fat: 13.5, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '6.012', nameVi: 'Bắp bò', nameEn: 'Beef shank', aliases: ['bap bo', 'bo bap', 'bap hoa', 'bap bo hoa'], kcal: 130, protein: 21.5, fat: 4.5, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '6.013', nameVi: 'Gân bò', nameEn: 'Beef tendon', aliases: ['gan bo', 'gan'], kcal: 110, protein: 24.0, fat: 1.0, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '6.014', nameVi: 'Xương bò', nameEn: 'Beef bones', aliases: ['xuong bo', 'xuong ong bo', 'xuong duoi bo', 'duoi bo'], kcal: 120, protein: 10.0, fat: 9.0, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '6.015', nameVi: 'Thịt gà (cả da)', nameEn: 'Chicken with skin', aliases: ['thit ga', 'ga', 'ga ta', 'ga cong nghiep', 'ga nguyen con', 'ga mai', 'dui ga', 'canh ga', 'thit ga ta', 'ga thit', 'ca ga', 'ga luoc'], kcal: 199, protein: 20.3, fat: 13.1, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '6.016', nameVi: 'Ức gà', nameEn: 'Chicken breast', aliases: ['uc ga', 'thit uc ga', 'uc ga phi le', 'phi le ga'], kcal: 110, protein: 23.0, fat: 1.5, carbs: 0.0, fiber: 0.0, sodiumMg: 65 },
  { fctCode: '6.017', nameVi: 'Thịt vịt', nameEn: 'Duck', aliases: ['thit vit', 'vit', 'vit nguyen con', 'vit co', 'vit xiem'], kcal: 267, protein: 17.8, fat: 21.8, carbs: 0.0, fiber: 0.0, sodiumMg: 80 },
  { fctCode: '6.018', nameVi: 'Thịt dê', nameEn: 'Goat', aliases: ['thit de', 'de'], kcal: 122, protein: 20.7, fat: 4.3, carbs: 0.0, fiber: 0.0, sodiumMg: 80 },
  { fctCode: '6.019', nameVi: 'Thịt ếch', nameEn: 'Frog', aliases: ['thit ech', 'ech'], kcal: 90, protein: 20.0, fat: 1.1, carbs: 0.0, fiber: 0.0, sodiumMg: 58 },
  { fctCode: '6.020', nameVi: 'Thịt trâu', nameEn: 'Buffalo', aliases: ['thit trau', 'trau'], kcal: 121, protein: 22.8, fat: 3.0, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '6.025', nameVi: 'Chả lụa (giò lụa)', nameEn: 'Vietnamese pork roll', aliases: ['cha lua', 'gio lua', 'cha', 'gio', 'cha hue', 'cha que', 'gio cha'], kcal: 136, protein: 21.5, fat: 5.5, carbs: 0.0, fiber: 0.0, sodiumMg: 800 },
  { fctCode: '6.026', nameVi: 'Chả cua / chả cá', nameEn: 'Fish/crab cake', aliases: ['cha cua', 'cha ca', 'cha cua hue', 'cha tom', 'cha ca thac lac', 'ca thac lac'], kcal: 150, protein: 18.0, fat: 7.0, carbs: 4.0, fiber: 0.0, sodiumMg: 700 },
  { fctCode: '6.027', nameVi: 'Xúc xích', nameEn: 'Sausage', aliases: ['xuc xich', 'lap xuong', 'jambon'], kcal: 300, protein: 14.0, fat: 26.0, carbs: 3.0, fiber: 0.0, sodiumMg: 900 },
  { fctCode: '6.028', nameVi: 'Pate gan', nameEn: 'Liver pate', aliases: ['pate', 'pa te', 'pate gan'], kcal: 320, protein: 11.5, fat: 28.0, carbs: 5.0, fiber: 0.0, sodiumMg: 750 },
  { fctCode: '6.029', nameVi: 'Thịt nguội / Thịt xông khói', nameEn: 'Ham / Bacon', aliases: ['thit nguoi', 'thit xong khoi', 'ba roi xong khoi', 'bacon', 'jambon'], kcal: 250, protein: 15.0, fat: 20.0, carbs: 1.5, fiber: 0.0, sodiumMg: 1200 },

  // ── 7. Thủy hải sản ───────────────────────────────────────────────────────
  { fctCode: '7.001', nameVi: 'Cá lóc (cá quả)', nameEn: 'Snakehead fish', aliases: ['ca loc', 'ca qua', 'ca chuoi'], kcal: 97, protein: 18.2, fat: 2.7, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '7.002', nameVi: 'Cá chép', nameEn: 'Carp', aliases: ['ca chep'], kcal: 96, protein: 16.0, fat: 3.6, carbs: 0.0, fiber: 0.0, sodiumMg: 50 },
  { fctCode: '7.003', nameVi: 'Cá rô phi / cá diêu hồng', nameEn: 'Tilapia', aliases: ['ca ro phi', 'ca dieu hong', 'ca ro'], kcal: 100, protein: 19.7, fat: 2.3, carbs: 0.0, fiber: 0.0, sodiumMg: 55 },
  { fctCode: '7.004', nameVi: 'Cá basa / cá tra', nameEn: 'Pangasius', aliases: ['ca basa', 'ca tra', 'phi le ca basa', 'ca ba sa'], kcal: 170, protein: 15.0, fat: 12.0, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '7.005', nameVi: 'Cá thu', nameEn: 'Mackerel', aliases: ['ca thu', 'ca thu ngu'], kcal: 166, protein: 18.2, fat: 10.3, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '7.006', nameVi: 'Cá ngừ', nameEn: 'Tuna', aliases: ['ca ngu', 'ca ngu dai duong', 'ca ngu hop'], kcal: 87, protein: 21.0, fat: 0.3, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '7.007', nameVi: 'Cá hồi', nameEn: 'Salmon', aliases: ['ca hoi', 'phi le ca hoi'], kcal: 136, protein: 22.0, fat: 5.3, carbs: 0.0, fiber: 0.0, sodiumMg: 50 },
  { fctCode: '7.008', nameVi: 'Cá nục', nameEn: 'Scad', aliases: ['ca nuc', 'ca bac ma', 'ca nuc hoa'], kcal: 111, protein: 20.2, fat: 3.3, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '7.009', nameVi: 'Cá trê / cá bống', nameEn: 'Catfish / goby', aliases: ['ca tre', 'ca bong', 'ca bong keo', 'ca keo'], kcal: 125, protein: 17.0, fat: 6.5, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '7.010', nameVi: 'Cá (chung)', nameEn: 'Fish, generic', aliases: ['ca', 'ca tuoi', 'ca bien', 'phi le ca', 'ca phi le', 'ca song', 'ca dieu', 'ca kho', 'ca trich', 'ca com', 'ca linh', 'ca he'], kcal: 110, protein: 18.5, fat: 4.0, carbs: 0.0, fiber: 0.0, sodiumMg: 60 },
  { fctCode: '7.015', nameVi: 'Tôm (tôm sú, tôm thẻ)', nameEn: 'Shrimp', aliases: ['tom', 'tom su', 'tom the', 'tom tuoi', 'tom bien', 'tom dong', 'tom bac', 'tom dat'], kcal: 90, protein: 18.4, fat: 1.8, carbs: 0.0, fiber: 0.0, sodiumMg: 150 },
  { fctCode: '7.016', nameVi: 'Tôm khô', nameEn: 'Dried shrimp', aliases: ['tom kho', 'tep kho', 'tom kho'], kcal: 347, protein: 75.6, fat: 3.8, carbs: 2.5, fiber: 0.0, sodiumMg: 1500 },
  { fctCode: '7.017', nameVi: 'Tép', nameEn: 'Small shrimp', aliases: ['tep', 'tep tuoi', 'tep dong', 'ruoc'], kcal: 60, protein: 11.7, fat: 1.2, carbs: 0.0, fiber: 0.0, sodiumMg: 140 },
  { fctCode: '7.020', nameVi: 'Mực tươi', nameEn: 'Squid', aliases: ['muc', 'muc tuoi', 'muc ong', 'muc la', 'muc nang'], kcal: 73, protein: 16.3, fat: 0.9, carbs: 0.0, fiber: 0.0, sodiumMg: 110 },
  { fctCode: '7.021', nameVi: 'Mực khô', nameEn: 'Dried squid', aliases: ['muc kho', 'kho muc'], kcal: 291, protein: 60.1, fat: 4.5, carbs: 2.5, fiber: 0.0, sodiumMg: 1000 },
  { fctCode: '7.025', nameVi: 'Cua đồng', nameEn: 'Field crab', aliases: ['cua dong', 'cua', 'rieu cua', 'cua xay'], kcal: 87, protein: 12.3, fat: 3.3, carbs: 2.0, fiber: 0.0, sodiumMg: 200 },
  { fctCode: '7.026', nameVi: 'Cua biển / ghẹ', nameEn: 'Sea crab', aliases: ['cua bien', 'ghe', 'thit cua', 'cua thit', 'cua gach'], kcal: 103, protein: 17.5, fat: 0.6, carbs: 7.0, fiber: 0.0, sodiumMg: 300 },
  { fctCode: '7.030', nameVi: 'Nghêu / sò / hến', nameEn: 'Clams', aliases: ['ngheu', 'so', 'hen', 'thit hen', 'so huyet', 'so diep', 'oc', 'oc buou', 'thit ngheu', 'vem', 'chem chep', 'trai'], kcal: 50, protein: 8.0, fat: 1.0, carbs: 2.0, fiber: 0.0, sodiumMg: 300 },
  { fctCode: '7.031', nameVi: 'Lươn', nameEn: 'Eel', aliases: ['luon', 'thit luon'], kcal: 94, protein: 20.0, fat: 1.5, carbs: 0.0, fiber: 0.0, sodiumMg: 70 },
  { fctCode: '7.035', nameVi: 'Cá khô', nameEn: 'Dried fish', aliases: ['ca kho', 'kho ca', 'ca kho kho', 'kho ca loc', 'kho ca sac'], kcal: 300, protein: 55.0, fat: 7.0, carbs: 2.0, fiber: 0.0, sodiumMg: 2000 },

  // ── 8. Trứng, sữa ─────────────────────────────────────────────────────────
  { fctCode: '8.001', nameVi: 'Trứng gà', nameEn: 'Chicken egg', aliases: ['trung ga', 'trung', 'qua trung', 'trung ga ta', 'long do trung', 'long trang trung', 'trung ga cong nghiep'], kcal: 166, protein: 14.8, fat: 11.6, carbs: 0.5, fiber: 0.0, sodiumMg: 158 },
  { fctCode: '8.002', nameVi: 'Trứng vịt', nameEn: 'Duck egg', aliases: ['trung vit', 'hot vit', 'trung vit lon', 'hot vit lon', 'trung vit muoi', 'trung muoi'], kcal: 184, protein: 13.0, fat: 14.2, carbs: 1.0, fiber: 0.0, sodiumMg: 190 },
  { fctCode: '8.003', nameVi: 'Trứng cút', nameEn: 'Quail egg', aliases: ['trung cut', 'trung chim cut'], kcal: 154, protein: 13.1, fat: 11.1, carbs: 0.4, fiber: 0.0, sodiumMg: 140 },
  { fctCode: '8.010', nameVi: 'Sữa tươi', nameEn: 'Whole milk', aliases: ['sua tuoi', 'sua', 'sua bo', 'sua tuoi khong duong', 'sua tuoi co duong'], kcal: 74, protein: 3.9, fat: 4.4, carbs: 4.8, fiber: 0.0, sodiumMg: 50 },
  { fctCode: '8.011', nameVi: 'Sữa đặc có đường', nameEn: 'Sweetened condensed milk', aliases: ['sua dac', 'sua dac co duong', 'sua ong tho'], kcal: 336, protein: 8.1, fat: 8.8, carbs: 56.0, fiber: 0.0, sodiumMg: 130 },
  { fctCode: '8.012', nameVi: 'Sữa chua', nameEn: 'Yogurt', aliases: ['sua chua', 'yaourt', 'yogurt'], kcal: 61, protein: 3.3, fat: 3.0, carbs: 5.0, fiber: 0.0, sodiumMg: 50 },
  { fctCode: '8.013', nameVi: 'Phô mai', nameEn: 'Cheese', aliases: ['pho mai', 'phomai', 'cheese', 'pho mai mozzarella', 'pho mai con bo cuoi'], kcal: 350, protein: 25.0, fat: 27.0, carbs: 1.5, fiber: 0.0, sodiumMg: 650 },
  { fctCode: '8.014', nameVi: 'Bơ (bơ động vật)', nameEn: 'Butter', aliases: ['bo lat', 'bo dong vat', 'bo thuc vat', 'bo'], kcal: 756, protein: 0.5, fat: 83.5, carbs: 0.5, fiber: 0.0, sodiumMg: 11 },
  { fctCode: '8.015', nameVi: 'Kem tươi (whipping cream)', nameEn: 'Whipping cream', aliases: ['kem tuoi', 'whipping cream', 'heavy cream', 'kem sua'], kcal: 340, protein: 2.1, fat: 36.0, carbs: 2.8, fiber: 0.0, sodiumMg: 38 },
  { fctCode: '8.016', nameVi: 'Sữa đậu nành', nameEn: 'Soy milk', aliases: ['sua dau nanh'], kcal: 28, protein: 3.1, fat: 1.6, carbs: 0.4, fiber: 0.0, sodiumMg: 10 },

  // ── 9. Dầu mỡ ─────────────────────────────────────────────────────────────
  { fctCode: '9.001', nameVi: 'Dầu ăn (dầu thực vật)', nameEn: 'Vegetable oil', aliases: ['dau an', 'dau', 'dau thuc vat', 'dau dau nanh', 'dau huong duong', 'dau oliu', 'dau o liu', 'dau me', 'dau phong', 'dau hat cai', 'dau dua', 'dau chien'], kcal: 897, protein: 0.0, fat: 99.7, carbs: 0.0, fiber: 0.0, sodiumMg: 0 },
  { fctCode: '9.002', nameVi: 'Mỡ heo (mỡ nước)', nameEn: 'Lard', aliases: ['mo nuoc', 'mo heo nuoc', 'mo lon nuoc'], kcal: 896, protein: 0.0, fat: 99.6, carbs: 0.0, fiber: 0.0, sodiumMg: 0 },
  { fctCode: '9.003', nameVi: 'Dầu điều (dầu màu điều)', nameEn: 'Annatto oil', aliases: ['dau dieu', 'dau mau dieu', 'hat dieu mau', 'mau dieu'], kcal: 884, protein: 0.0, fat: 98.0, carbs: 0.0, fiber: 0.0, sodiumMg: 0 },

  // ── 10. Gia vị, nước chấm ─────────────────────────────────────────────────
  { fctCode: '10.001', nameVi: 'Nước mắm', nameEn: 'Fish sauce', aliases: ['nuoc mam', 'mam', 'nuoc mam nhi', 'nuoc mam ngon', 'nuoc mam nam ngu', 'nuoc mam phu quoc'], kcal: 35, protein: 7.2, fat: 0.0, carbs: 1.5, fiber: 0.0, sodiumMg: 7720 },
  { fctCode: '10.002', nameVi: 'Nước tương (xì dầu)', nameEn: 'Soy sauce', aliases: ['nuoc tuong', 'xi dau', 'tuong', 'maggi', 'nuoc tuong maggi'], kcal: 53, protein: 5.2, fat: 0.5, carbs: 7.1, fiber: 0.0, sodiumMg: 5600 },
  { fctCode: '10.003', nameVi: 'Mắm tôm', nameEn: 'Shrimp paste', aliases: ['mam tom', 'mam tom bac'], kcal: 73, protein: 14.8, fat: 1.5, carbs: 0.0, fiber: 0.0, sodiumMg: 7000 },
  { fctCode: '10.004', nameVi: 'Mắm ruốc', nameEn: 'Fermented shrimp paste (Hue)', aliases: ['mam ruoc', 'ruoc hue', 'mam ruoc hue'], kcal: 85, protein: 16.0, fat: 1.8, carbs: 1.0, fiber: 0.0, sodiumMg: 6500 },
  { fctCode: '10.005', nameVi: 'Mắm nêm / mắm cá', nameEn: 'Fermented fish sauce', aliases: ['mam nem', 'mam ca', 'mam ca linh', 'mam ca sac', 'mam bo hoc', 'mam ca loc'], kcal: 70, protein: 12.0, fat: 1.0, carbs: 2.5, fiber: 0.0, sodiumMg: 6000 },
  { fctCode: '10.006', nameVi: 'Muối', nameEn: 'Salt', aliases: ['muoi', 'muoi an', 'muoi hat', 'muoi tinh', 'muoi bien', 'muoi i ot'], kcal: 0, protein: 0.0, fat: 0.0, carbs: 0.0, fiber: 0.0, sodiumMg: 38758 },
  { fctCode: '10.007', nameVi: 'Đường cát (saccharose)', nameEn: 'Sugar', aliases: ['duong', 'duong cat', 'duong trang', 'duong vang', 'duong kinh', 'duong cat trang', 'duong nau', 'duong bot'], kcal: 397, protein: 0.0, fat: 0.0, carbs: 99.3, fiber: 0.0, sodiumMg: 1 },
  { fctCode: '10.008', nameVi: 'Đường phèn', nameEn: 'Rock sugar', aliases: ['duong phen'], kcal: 390, protein: 0.0, fat: 0.0, carbs: 97.5, fiber: 0.0, sodiumMg: 1 },
  { fctCode: '10.009', nameVi: 'Đường thốt nốt', nameEn: 'Palm sugar', aliases: ['duong thot not', 'duong tho not'], kcal: 380, protein: 0.2, fat: 0.0, carbs: 94.0, fiber: 0.0, sodiumMg: 30 },
  { fctCode: '10.010', nameVi: 'Mật ong', nameEn: 'Honey', aliases: ['mat ong'], kcal: 327, protein: 0.4, fat: 0.0, carbs: 81.3, fiber: 0.0, sodiumMg: 4 },
  { fctCode: '10.011', nameVi: 'Bột ngọt (mì chính)', nameEn: 'MSG', aliases: ['bot ngot', 'mi chinh', 'ajinomoto'], kcal: 0, protein: 0.0, fat: 0.0, carbs: 0.0, fiber: 0.0, sodiumMg: 12300 },
  { fctCode: '10.012', nameVi: 'Hạt nêm', nameEn: 'Seasoning granules', aliases: ['hat nem', 'hat nem knorr', 'bot nem', 'bot canh', 'gia vi'], kcal: 180, protein: 12.0, fat: 2.0, carbs: 28.0, fiber: 0.0, sodiumMg: 18000 },
  { fctCode: '10.013', nameVi: 'Tiêu', nameEn: 'Black pepper', aliases: ['tieu', 'hat tieu', 'tieu xay', 'tieu den', 'tieu so', 'tieu xanh'], kcal: 231, protein: 7.0, fat: 7.4, carbs: 34.1, fiber: 14.1, sodiumMg: 44 },
  { fctCode: '10.014', nameVi: 'Ớt bột / Ớt khô', nameEn: 'Chili powder', aliases: ['ot bot', 'ot kho', 'bot ot', 'ot xay', 'ot kho xay'], kcal: 282, protein: 12.0, fat: 14.3, carbs: 32.5, fiber: 25.0, sodiumMg: 30 },
  { fctCode: '10.015', nameVi: 'Sa tế', nameEn: 'Satay chili oil', aliases: ['sa te', 'sate', 'ot sa te'], kcal: 520, protein: 4.0, fat: 52.0, carbs: 10.0, fiber: 3.0, sodiumMg: 1500 },
  { fctCode: '10.016', nameVi: 'Tương ớt', nameEn: 'Chili sauce', aliases: ['tuong ot', 'tuong ot chinsu'], kcal: 110, protein: 1.5, fat: 0.5, carbs: 25.0, fiber: 1.5, sodiumMg: 1800 },
  { fctCode: '10.017', nameVi: 'Tương cà', nameEn: 'Ketchup', aliases: ['tuong ca', 'sot ca chua', 'ketchup'], kcal: 100, protein: 1.2, fat: 0.2, carbs: 24.0, fiber: 0.5, sodiumMg: 900 },
  { fctCode: '10.018', nameVi: 'Dấm (giấm)', nameEn: 'Vinegar', aliases: ['giam', 'dam', 'giam gao', 'giam an', 'giam tao'], kcal: 18, protein: 0.0, fat: 0.0, carbs: 0.4, fiber: 0.0, sodiumMg: 2 },
  { fctCode: '10.019', nameVi: 'Dầu hào', nameEn: 'Oyster sauce', aliases: ['dau hao'], kcal: 110, protein: 2.5, fat: 0.5, carbs: 23.0, fiber: 0.0, sodiumMg: 2700 },
  { fctCode: '10.020', nameVi: 'Tương hột / Tương bần', nameEn: 'Fermented soybean paste', aliases: ['tuong hot', 'tuong ban', 'tuong dau', 'tuong den', 'tuong hoisin', 'sot hoisin'], kcal: 130, protein: 8.0, fat: 3.0, carbs: 15.0, fiber: 2.0, sodiumMg: 3500 },
  { fctCode: '10.021', nameVi: 'Chao', nameEn: 'Fermented tofu', aliases: ['chao', 'chao do', 'chao trang'], kcal: 116, protein: 8.2, fat: 8.0, carbs: 2.5, fiber: 0.0, sodiumMg: 2800 },
  { fctCode: '10.022', nameVi: 'Ngũ vị hương', nameEn: 'Five spice', aliases: ['ngu vi huong', 'bot ngu vi huong', 'bot ca ri', 'ca ri', 'bot cari', 'hoi', 'que', 'thao qua', 'dinh huong', 'hat ngo'], kcal: 300, protein: 7.0, fat: 6.0, carbs: 55.0, fiber: 20.0, sodiumMg: 50 },
  { fctCode: '10.023', nameVi: 'Rượu nấu ăn', nameEn: 'Cooking wine', aliases: ['ruou', 'ruou trang', 'ruou nau an', 'ruou gao', 'ruou mai que lo'], kcal: 150, protein: 0.0, fat: 0.0, carbs: 2.0, fiber: 0.0, sodiumMg: 5 },
  { fctCode: '10.024', nameVi: 'Nước cốt chanh dây / siro', nameEn: 'Syrup', aliases: ['siro', 'si ro', 'nuoc duong', 'nuoc duong banh'], kcal: 260, protein: 0.0, fat: 0.0, carbs: 65.0, fiber: 0.0, sodiumMg: 10 },
  { fctCode: '10.025', nameVi: 'Nước lọc', nameEn: 'Water', aliases: ['nuoc', 'nuoc loc', 'nuoc soi', 'nuoc lanh', 'nuoc am', 'nuoc dun soi', 'nuoc dung', 'nuoc ham xuong', 'nuoc le'], kcal: 0, protein: 0.0, fat: 0.0, carbs: 0.0, fiber: 0.0, sodiumMg: 2 },
  { fctCode: '10.026', nameVi: 'Bột nở / baking', nameEn: 'Baking powder', aliases: ['bot no', 'baking powder', 'baking soda', 'men no', 'men', 'men banh mi', 'bot khai'], kcal: 50, protein: 0.0, fat: 0.0, carbs: 24.0, fiber: 0.0, sodiumMg: 10000 },
  { fctCode: '10.027', nameVi: 'Ca cao / Cà phê bột', nameEn: 'Cocoa / coffee', aliases: ['ca cao', 'bot ca cao', 'ca phe', 'cafe', 'bot ca phe', 'ca phe bot'], kcal: 300, protein: 15.0, fat: 12.0, carbs: 45.0, fiber: 25.0, sodiumMg: 20 },
  { fctCode: '10.028', nameVi: 'Trà', nameEn: 'Tea', aliases: ['tra', 'tra xanh', 'la tra', 'tra tui loc', 'tra den', 'bot tra xanh', 'matcha'], kcal: 0, protein: 0.0, fat: 0.0, carbs: 0.0, fiber: 0.0, sodiumMg: 1 },
  { fctCode: '10.029', nameVi: 'Lá dứa', nameEn: 'Pandan leaf', aliases: ['la dua', 'la nep'], kcal: 20, protein: 1.0, fat: 0.2, carbs: 4.0, fiber: 2.0, sodiumMg: 5 },
  { fctCode: '10.030', nameVi: 'Bột sắn dây / rau câu / thạch', nameEn: 'Agar / jelly powder', aliases: ['rau cau', 'bot rau cau', 'thach', 'bot san day', 'san day', 'gelatin'], kcal: 300, protein: 1.0, fat: 0.0, carbs: 75.0, fiber: 8.0, sodiumMg: 100 },
  { fctCode: '10.031', nameVi: 'Hành phi / tỏi phi', nameEn: 'Fried shallots', aliases: ['hanh phi san', 'toi phi san'], kcal: 450, protein: 5.0, fat: 35.0, carbs: 30.0, fiber: 3.0, sodiumMg: 200 },
  { fctCode: '10.032', nameVi: 'Bánh phồng tôm', nameEn: 'Prawn cracker', aliases: ['banh phong tom', 'phong tom'], kcal: 540, protein: 5.0, fat: 32.0, carbs: 60.0, fiber: 0.5, sodiumMg: 900 },
  { fctCode: '10.033', nameVi: 'Nước dùng gà / bò (hộp)', nameEn: 'Broth', aliases: ['nuoc dung ga', 'nuoc dung bo', 'nuoc ham ga', 'nuoc ham bo', 'nuoc luoc ga', 'nuoc dung'], kcal: 8, protein: 1.0, fat: 0.3, carbs: 0.5, fiber: 0.0, sodiumMg: 350 },
];
