/**
 * BA-005 Weekly Meal Plan — Error codes (mục 14 BA-005)
 */
export const WEEKLY_PLAN_ERRORS = {
  CONFIG_NOT_FOUND: 'WEEKLY_PLAN_CONFIG_NOT_FOUND',
  PLAN_NOT_FOUND: 'WEEKLY_PLAN_NOT_FOUND',
  SLOT_NOT_FOUND: 'WEEKLY_PLAN_SLOT_NOT_FOUND',
  SLOT_LOCKED: 'WEEKLY_PLAN_SLOT_LOCKED',
  SLOT_NOT_PLANNED: 'WEEKLY_PLAN_SLOT_NOT_PLANNED',
  PLAN_NOT_READY: 'WEEKLY_PLAN_NOT_READY',
  PLAN_NOT_ACTIVE: 'WEEKLY_PLAN_NOT_ACTIVE',
  PLAN_ALREADY_ACTIVE: 'WEEKLY_PLAN_ALREADY_ACTIVE',
  PLAN_GENERATING: 'WEEKLY_PLAN_GENERATING',
  PLAN_VERSION_CONFLICT: 'WEEKLY_PLAN_VERSION_CONFLICT',
  INSUFFICIENT_CANDIDATES: 'WEEKLY_PLAN_INSUFFICIENT_CANDIDATES',
  BUDGET_EXCEEDED: 'WEEKLY_PLAN_BUDGET_EXCEEDED',
  KCAL_OUT_OF_RANGE: 'WEEKLY_PLAN_KCAL_OUT_OF_RANGE',
  GENERATION_FAILED: 'WEEKLY_PLAN_GENERATION_FAILED',
  SWAP_DISH_NOT_FOUND: 'WEEKLY_PLAN_SWAP_DISH_NOT_FOUND',
  SWAP_BUDGET_EXCEEDED: 'WEEKLY_PLAN_SWAP_BUDGET_EXCEEDED',
  FORBIDDEN: 'WEEKLY_PLAN_FORBIDDEN',
} as const;

export type WeeklyPlanErrorCode = (typeof WEEKLY_PLAN_ERRORS)[keyof typeof WEEKLY_PLAN_ERRORS];
